assign:
  issues: disabled
  pull_requests: disabled

  strategy:
    # random
    daily-shift-based
  schedule:
    '*/1 * * * *'
  assignees:
    - yhcc
    - yhcc
    - sunpengsdu
    - sunpengsdu
    - ZwwWayne
    - ZwwWayne
    - yhcc
