name: 🐞 Bug report
description: Create a report to help us improve
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        ## Note
        For general usage questions or idea discussions, please post it to our [**Forum**](https://github.com/InternLM/InternLM/discussions)
        Please fill in as **much** of the following form as you're able to. **The clearer the description, the shorter it will take to solve it.**

  - type: markdown
    attributes:
      value: |
        If you have already identified the reason, we strongly appreciate you creating a new PR!
        If you need our help, please fill in the following form to help us to identify the bug.

  - type: textarea
    id: describe
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: |
        Please provide a clear and concise description of what the bug is.
        Preferably a simple and minimal code snippet that we can reproduce the error by running the code.
      placeholder: |
        A clear and concise description of what the bug is.

        ```python
        # Sample code to reproduce the problem
        ```

        ```shell
        The command or script you run.
        ```

        ```
        The error message or logs you got, with the full traceback.
        ```

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: Environment
      description: |
        Please check the torch version and cuda version and fill in the following table.
      placeholder: |
        ```python
        # The output the above command
        ```

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        Tell us anything else you think we should know.

        1. Did you make any modifications on the code or config?
        2. What do you think might be the reason?

  - type: markdown
    attributes:
      value: |
        ## Acknowledgement
        Thanks for taking the time to fill out this report.

        If you have already identified the reason, we strongly appreciate you creating a new PR to fix it [**here**](https://github.com/InternLM/InternLM/pulls)!
