name: 🐞 报告 Bug
description: 报告你在使用中遇到的不合预期的情况
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        ## 注意
        对于一般的使用问题或者想法讨论，请在我们的[**论坛**](https://github.com/InternLM/InternLM/discussions)
        请尽可能填写以下表格。**描述得越清楚，解决问题的时间就越短。**

  - type: markdown
    attributes:
      value: |
        我们推荐使用英语模板 Bug report，以便你的问题帮助更多人。

        如果你已经有了解决方案，我们非常欢迎你直接创建一个新的 PR 来解决这个问题。
        如果你需要我们的帮助，请填写以下内容帮助我们定位 Bug。

  - type: textarea
    id: describe
    validations:
      required: true
    attributes:
      label: 描述该错误
      description: |
        请简要说明你遇到的错误。如果可以的话，请提供一个简短的代码片段帮助我们复现这一错误。
      placeholder: |
        问题的简要说明

        ```python
        # 复现错误的代码片段
        ```

        ```shell
        # 发生错误时你的运行命令
        ```

        ```
        错误信息和日志，请展示全部的错误日志和 traceback
        ```

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: 环境信息
      description: |
        请检查 pytorch/CUDA 环境的信息，并贴在下方。
      placeholder: |
        ```python
        # 上述命令的输出
        ```

  - type: textarea
    id: other
    attributes:
      label: 其他信息
      description: |
        告诉我们其他有价值的信息。

        1. 你是否对代码或配置文件做了任何改动？
        2. 你认为可能的原因是什么？

  - type: markdown
    attributes:
      value: |
        ## 致谢
        感谢你的反馈！

        如果你已经找到了错误的原因，我们非常欢迎你直接创建一个新的 PR 来解决这个问题 [**here**](https://github.com/InternLM/InternLM/pulls)!
