name: 📚 文档
description: 提出文档中的错误或者提出文档改进的建议
labels: "documentation"
title: "[Docs] "

body:
  - type: markdown
    attributes:
      value: |
        ## 注意
        对于一般的使用问题或者想法讨论，请在我们的[**论坛**](https://github.com/InternLM/InternLM/discussions)
        请尽可能填写以下表格。**描述得越清楚，解决问题的时间就越短。**


  - type: textarea
    attributes:
      label: 📚 描述文档中的错误
      description: >
        请简要说明你在文档中发现的错误
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📚 描述文档中的改进建议
      description: >
        请简要说明你对文档的改进建议

  - type: markdown
    attributes:
      value: |
        ## 致谢
        感谢你的反馈！

        如果你已经找到了错误的原因，我们非常欢迎你直接创建一个新的 PR 来解决这个问题 [**here**](https://github.com/InternLM/InternLM/pulls)!
