name: debug
on: 
  push:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "**.md"
jobs:
  check-requirements:
    runs-on: [lmtest]
    steps:
    - uses: actions/checkout@v3
      with:
         fetch-depth: 2
    - name: check-requirements
      run: |
        echo "debuging"
        
